void check_malloc(double *m1);
void get_dim(int *rows, int *cols);
void insert_matrix(double *m, int rows, int cols);
void print_matrix(double *m, int rows, int cols, int *ans);
void print_result(double *m, int rows, int cols);
double *sum_matrix(double*m, double *m1, int rows, int cols);
void prod_scalar(double *m, int rows, int cols, double scalar);
double determinant(double *m, int rows, int cols);
double * transpose(double *m, int rows, int cols);
double *rows_cols(double *m, double *m1, int rows, int cols, int rows1, int cols1);
int check_ifDiag(double *m, int rows, int cols);
int inf_diag(double *m, int rows, int cols);
int sup_diag(double *m, int rows, int cols);
int zero_row(double *m, int rows, int cols);
int zero_col(double *m, int rows, int cols);
int equal_row(double*m, int rows, int cols);
int equal_col(double *m, int rows, int cols);
double *algebrics(double *m, int rows, int cols);
void first_operation(double *rh, double *rk, int cols);
void second_operation(double *rh, int scalar, int cols);
void third_operation(double *matrix, int rows, int cols);
int allZeros(double *matrix, int cols);