int mcd(int a, int b);
int solve(int a, int b, int mod);
void check_mallocN(int *m1);
void get_dimN(int *rows, int *cols);
void insert_matrixN(int *m, int rows, int cols, int n);
void print_matrixN(int *m, int rows, int cols, int *ans);
void print_resultN(int *m, int rows, int cols);
int *sum_matrixN(int*m, int *m1, int rows, int cols, int n);
void prod_scalarN(int *m, int rows, int cols, int scalar, int n);
int determinantN(int *m, int rows, int cols, int n);
int *transposeN(int *m, int rows, int cols);
int *rows_colsN(int *m, int *m1, int rows, int cols, int rows1, int cols1, int n);
int check_ifDiagN(int *m, int rows, int cols);
int inf_diagN(int *m, int rows, int cols);
int sup_diagN(int *m, int rows, int cols);
int zero_rowN(int *m, int rows, int cols);
int zero_colN(int *m, int rows, int cols);
int equal_rowN(int*m, int rows, int cols);
int equal_colN(int *m, int rows, int cols);
int *algebricsN(int *m, int rows, int cols, int n);